### ISSUE TITLE
CrashLoopBackOff when install kube-ovn by kube-ovn.yaml

### ISSUE THREAD

**Issue by manshuxu** [alauda/kube-ovn#55]
kube-ovn component status aflter "kubectl apply -f kube-ovn.yaml" in step 3.
```
# kubectl    -n kube-ovn  get po
NAME                                  READY   STATUS             RESTARTS   AGE
kube-ovn-cni-nj5rp                    0/1     CrashLoopBackOff   8          18m
kube-ovn-cni-rxnmw                    0/1     CrashLoopBackOff   8          18m
kube-ovn-cni-zrkkd                    0/1     CrashLoopBackOff   8          18m
kube-ovn-controller-75fbd69f4-cpz26   0/1     CrashLoopBackOff   8          18m
kube-ovn-controller-75fbd69f4-w4xbt   0/1     CrashLoopBackOff   8          18m
ovn-central-74f6567dfd-5m6fd          1/1     Running            0          13h
ovs-ovn-jlx7j                         1/1     Running            0          13h
ovs-ovn-llfhm                         1/1     Running            0          13h
ovs-ovn-n5xlp                         1/1     Running            0          13h
```

logs of kube-ovn-cni
```
# kubectl    -n kube-ovn  logs -f kube-ovn-cni-nj5rp 
I0709 01:57:49.380862   28682 config.go:128] no --kubeconfig, use in-cluster kubernetes config
I0709 01:57:49.382146   28682 config.go:120] daemon config: &{eth0 1442 /run/openvswitch/kube-ovn-daemon.sock /run/openvswitch/db.sock  0xc00018f0e0 centos93 10.96.0.0/12 10665}
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/alauda/kube-ovn/pkg/daemon.InitNodeGateway(0xc000110600, 0x0, 0x0)
	/Users/oilbeater/workspace/src/github.com/alauda/kube-ovn/pkg/daemon/init.go:32 +0x68b
main.main()
	/Users/oilbeater/workspace/src/github.com/alauda/kube-ovn/cmd/daemon/cniserver.go:27 +0x10d
```

logs of kube-ovn-controller
```
# kubectl    -n kube-ovn  logs -f kube-ovn-controller-75fbd69f4-cpz26
I0709 02:02:48.643986       1 config.go:143] no --kubeconfig, use in-cluster kubernetes config
I0709 02:02:48.645605       1 config.go:134] config is  &{  10.98.181.28 6641  0xc00011c900 ovn-default 10.16.0.0/16 10.16.0.1 10.16.0.1 ovn-cluster join 100.64.0.0/16 100.64.0.1 cluster-tcp-loadbalancer cluster-udp-loadbalancer kube-ovn-controller-75fbd69f4-cpz26 kube-ovn 3 10660}
I0709 02:02:48.651209       1 ovn-nbctl.go:20] ovn-nbctl command lr-list in 5ms
I0709 02:02:48.651257       1 init.go:81] exists routers [ovn-cluster]
I0709 02:02:48.655191       1 ovn-nbctl.go:20] ovn-nbctl command --data=bare --no-heading --columns=_uuid find load_balancer name=cluster-tcp-loadbalancer in 3ms
I0709 02:02:48.655257       1 init.go:105] tcp load balancer 079ec34a-8e45-43a4-9bc7-5585c4d18fc6 exists
I0709 02:02:48.658555       1 ovn-nbctl.go:20] ovn-nbctl command --data=bare --no-heading --columns=_uuid find load_balancer name=cluster-udp-loadbalancer in 3ms
I0709 02:02:48.658580       1 init.go:120] udp load balancer 824cdb69-1870-44ee-895f-b114b8ddf5b9 exists
I0709 02:02:48.661792       1 ovn-nbctl.go:20] ovn-nbctl command ls-list in 3ms
I0709 02:02:48.661846       1 init.go:60] exists switches [join]
E0709 02:02:48.690642       1 init.go:48] patch namespace kube-ovn failed namespaces "kube-ovn" is forbidden: User "system:serviceaccount:kube-ovn:ovn" cannot patch resource "namespaces" in API group "" in the namespace "kube-ovn"
E0709 02:02:48.690959       1 controller.go:53] init default switch failed namespaces "kube-ovn" is forbidden: User "system:serviceaccount:kube-ovn:ovn" cannot patch resource "namespaces" in API group "" in the namespace "kube-ovn"
```
kubernetes version
```
# kubectl version
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.5", GitCommit:"51dd616cdd25d6ee22c83a858773b607328a18ec", GitTreeState:"clean", BuildDate:"2019-01-16T18:24:45Z", GoVersion:"go1.10.7", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.5", GitCommit:"51dd616cdd25d6ee22c83a858773b607328a18ec", GitTreeState:"clean", BuildDate:"2019-01-16T18:14:49Z", GoVersion:"go1.10.7", Compiler:"gc", Platform:"linux/amd64"}
```

appreciate if there is any help

**Comment by oilbeater** [comment]
Seems like we miss a rules to add patch privilege to clusterrole. You can edit the `system:ovn-reader` ClusterRole and add a patch verb to namespaces resource

**Comment by manshuxu** [comment]
In my k8s cluster, we lost ClusterRole ```cluster-admin``` by some reasones. so ClusterRole  ```system:ovn-reader``` is the only privileges provide for ovn-controller and ovn-cni, and the ```system:ovn-reader``` isn't satisfied.
